// ============================================================================
// 📊 trend_analytics_app/channels_db.js
// 6대 플랫폼(도우인, 틱톡, 유튜브, 샤오홍슈, 인스타, 스레드) 정밀 분석 데이터베이스
// 구독자수, 평균조회수, 좋아요, 댓글, 구독자대비조회수비율(떡상지수) 탑재
// ============================================================================

export const INITIAL_CHANNELS_DB = [
  // 🇨🇳 [도우인 / Douyin]
  {
    id: "dy_01",
    name: "美妆老爸 (페이스오프 변신)",
    handle: "@beauty_magic_dy",
    platform: "douyin",
    platformName: "도우인",
    platformIcon: "🇨🇳",
    category: "뷰티 / 홈케어",
    subscribers: 2400000,
    avgViews: 18500000,
    likes: 920000,
    comments: 48000,
    tags: ["뷰티", "리프팅", "페이스테이프", "비포애프터", "홈케어", "도우인변신"],
    url: "https://www.douyin.com/search/%E5%8F%98%E7%BE%8E%E7%A7%98%E7%B1%8D",
    highlight: "처진 턱선에 0.02mm 테이프를 붙이고 당기는 3초 컷으로 조회수 1800만 돌파. 극적인 비포/애프터 대비의 정석.",
    avatar: "💄"
  },
  {
    id: "dy_02",
    name: "小李的居家神器 (가성비 가젯)",
    handle: "@homeshare_dy",
    platform: "douyin",
    platformName: "도우인",
    platformIcon: "🇨🇳",
    category: "생활꿀템 / 가젯",
    subscribers: 450000,
    avgViews: 4200000,
    likes: 210000,
    comments: 12500,
    tags: ["생활꿀템", "가젯", "쿠팡소싱", "삶의질상승", "가성비", "자취템"],
    url: "https://www.douyin.com/search/%E5%B1%85%E5%AE%B6%E5%A5%BD%E7%89%A9",
    highlight: "구독자 45만 대비 평균 조회수 420만(933% 떡상). 첫 1초에 일상 속 빡치는 순간을 보여준 뒤 꿀템으로 쾌감 해결.",
    avatar: "🛠️"
  },
  {
    id: "dy_03",
    name: "董宇辉 (감성 스토리텔링 쇼핑)",
    handle: "@dongyuhui_dy",
    platform: "douyin",
    platformName: "도우인",
    platformIcon: "🇨🇳",
    category: "지식 / 쇼핑",
    subscribers: 26000000,
    avgViews: 32000000,
    likes: 2400000,
    comments: 180000,
    tags: ["지식", "스토리텔링", "도우인1등", "완판신화", "라이브커머스"],
    url: "https://www.douyin.com/search/%E8%91%A3%E5%AE%87%E8%BE%89",
    highlight: "물건의 기능을 나열하지 않고 시적인 감성과 인문학적 가치를 부여하여 구매 전환율을 극대화함.",
    avatar: "📚"
  },
  {
    id: "dy_04",
    name: "阿雅护肤日记 (스킨케어 꿀팁)",
    handle: "@aya_skin",
    platform: "douyin",
    platformName: "도우인",
    platformIcon: "🇨🇳",
    category: "뷰티 / 홈케어",
    subscribers: 120000,
    avgViews: 2800000,
    likes: 180000,
    comments: 9200,
    tags: ["뷰티", "홈케어", "콜라겐팩", "모공관리", "가성비", "올리브영"],
    url: "https://www.douyin.com/search/%E6%B2%89%E6%B5%B8%E5%BC%8F%E6%8A%A4%E8%82%A4",
    highlight: "구독자 12만 소형 채널이지만 조회수 280만(2,333% 폭발적 떡상)! ASMR 사운드와 초밀착 피부 카메라 연출.",
    avatar: "✨"
  },

  // 🌍 [틱톡 / TikTok]
  {
    id: "tt_01",
    name: "Khaby Lame",
    handle: "@khaby.lame",
    platform: "tiktok",
    platformName: "틱톡",
    platformIcon: "🌍",
    category: "라이프핵 / 유머",
    subscribers: 162000000,
    avgViews: 45000000,
    likes: 3800000,
    comments: 95000,
    tags: ["라이프핵", "무언극", "시그니처손동작", "글로벌1등", "생활꿀팁"],
    url: "https://www.tiktok.com/@khaby.lame",
    highlight: "말 한마디 없이 표정과 손짓 하나로 복잡한 해외 꿀팁을 풍자하며 전 세계 시청 지속시간 1위 달성.",
    avatar: "🤷‍♂️"
  },
  {
    id: "tt_02",
    name: "Mikayla Nogueira",
    handle: "@mikaylanogueira",
    platform: "tiktok",
    platformName: "틱톡",
    platformIcon: "🌍",
    category: "뷰티 / 솔직리뷰",
    subscribers: 15800000,
    avgViews: 12000000,
    likes: 1400000,
    comments: 32000,
    tags: ["뷰티", "솔직리뷰", "품절대란", "리프팅", "올리브영", "밀착발색"],
    url: "https://www.tiktok.com/@mikaylanogueira",
    highlight: "강렬한 첫마디 후킹과 노필터 피부 클로즈업으로 미국 세포라/아마존 품절 대란을 일으키는 바이럴 여왕.",
    avatar: "💄"
  },
  {
    id: "tt_03",
    name: "Viral Amazon Gadgets",
    handle: "@amazongadgets_daily",
    platform: "tiktok",
    platformName: "틱톡",
    platformIcon: "🌍",
    category: "생활꿀템 / 가젯",
    subscribers: 280000,
    avgViews: 3900000,
    likes: 290000,
    comments: 8400,
    tags: ["생활꿀템", "아마존가젯", "삶의질상승", "가성비", "자취템", "쿠팡소싱"],
    url: "https://www.tiktok.com/search?q=amazon%20finds",
    highlight: "구독자 28만인데 조회수 390만(1,392% 떡상). '내가 왜 이걸 이제야 샀을까?'라는 후킹 카피로 구매욕 자극.",
    avatar: "📦"
  },
  {
    id: "tt_04",
    name: "Korean Skin Lab",
    handle: "@k_glassskin",
    platform: "tiktok",
    platformName: "틱톡",
    platformIcon: "🌍",
    category: "뷰티 / K뷰티",
    subscribers: 540000,
    avgViews: 4800000,
    likes: 410000,
    comments: 11000,
    tags: ["뷰티", "K뷰티", "글래스스킨", "리프팅", "올리브영", "홈케어"],
    url: "https://www.tiktok.com/search?q=korean%20skincare%20routine",
    highlight: "한국 올리브영 꿀조합을 해외 시청자 눈높이로 번역하여 평균 888%의 높은 떡상 조회수 기록.",
    avatar: "🧴"
  },

  // ▶️ [유튜브 쇼츠 / YouTube Shorts]
  {
    id: "yt_01",
    name: "1분만",
    handle: "@1minute_know",
    platform: "youtube",
    platformName: "유튜브",
    platformIcon: "▶️",
    category: "지식 / 꿀팁",
    subscribers: 1280000,
    avgViews: 2400000,
    likes: 85000,
    comments: 3200,
    tags: ["지식", "생활꿀팁", "1분완성", "속사포나레이션", "호기심유발"],
    url: "https://www.youtube.com/@1minute_know",
    highlight: "0.1초 만에 귀를 사로잡는 보이스 텐션과 단어 싱크 자막으로 시청 지속률 95% 이상 방어.",
    avatar: "⏱️"
  },
  {
    id: "yt_02",
    name: "화장하는 청담언니",
    handle: "@cheongdam_makeup",
    platform: "youtube",
    platformName: "유튜브",
    platformIcon: "▶️",
    category: "뷰티 / 홈케어",
    subscribers: 1650000,
    avgViews: 3100000,
    likes: 120000,
    comments: 4100,
    tags: ["뷰티", "리프팅", "홈케어", "연예인비법", "올리브영", "비포애프터"],
    url: "https://www.youtube.com/results?search_query=%ED%99%94%EC%9E%A5%ED%95%98%EB%8A%94%EC%B2%AD%EB%8B%B4%EC%96%B8%EB%8B%88",
    highlight: "연예인 메이크업 샵의 턱선 브이라인 비법 및 모공 커버를 40초로 압축하여 쇼츠 알고리즘 장악.",
    avatar: "💋"
  },
  {
    id: "yt_03",
    name: "자취의신 (원룸 꿀템)",
    handle: "@god_of_room",
    platform: "youtube",
    platformName: "유튜브",
    platformIcon: "▶️",
    category: "생활꿀템 / 가젯",
    subscribers: 95000,
    avgViews: 1850000,
    likes: 74000,
    comments: 2900,
    tags: ["생활꿀템", "자취템", "다이소꿀템", "가성비", "삶의질상승", "쿠팡소싱"],
    url: "https://www.youtube.com/results?search_query=%EC%9E%90%EC%B7%A8%EA%BF%80%ED%85%9C",
    highlight: "구독자 9.5만 명인데 평균 조회수 185만(1,947% 압도적 떡상)! 다이소와 쿠팡의 숨겨진 가성비 꿀템 집중 조명.",
    avatar: "🏠"
  },
  {
    id: "yt_04",
    name: "잡식공룡",
    handle: "@dinoknow",
    platform: "youtube",
    platformName: "유튜브",
    platformIcon: "▶️",
    category: "테크 / 가젯",
    subscribers: 820000,
    avgViews: 1600000,
    likes: 58000,
    comments: 2100,
    tags: ["테크", "가젯", "팩트체크", "생활꿀팁", "신기한물건"],
    url: "https://www.youtube.com/results?search_query=%EC%9E%90%EB%B9%9D%EA%B3%B5%EB%A3%A1",
    highlight: "광고 협찬 없는 가차 없는 솔직 팩트 체크와 실제 분해/테스트로 구독자들의 절대적 신뢰 확보.",
    avatar: "🦖"
  },

  // 📕 [샤오홍슈 / Xiaohongshu]
  {
    id: "xhs_01",
    name: "成分控小徐 (성분 전문 닥터)",
    handle: "@skincare_doc_xhs",
    platform: "xiaohongshu",
    platformName: "샤오홍슈",
    platformIcon: "📕",
    category: "뷰티 / 성분분석",
    subscribers: 4200000,
    avgViews: 9500000,
    likes: 680000,
    comments: 31000,
    tags: ["뷰티", "성분분석", "홈케어", "리프팅", "안티에이징", "올리브영"],
    url: "https://www.xiaohongshu.com/search_result?keyword=%E6%8A%97%E8%80%81%E7%B4%A7%E8%87%B4",
    highlight: "화장품 성분표를 현미경으로 대조하며 턱선 리프팅과 피부 장벽 재생 조합을 과학적으로 입증.",
    avatar: "🔬"
  },
  {
    id: "xhs_02",
    name: "30초 홈케어 요정",
    handle: "@30s_homecare",
    platform: "xiaohongshu",
    platformName: "샤오홍슈",
    platformIcon: "📕",
    category: "뷰티 / 홈케어",
    subscribers: 180000,
    avgViews: 3200000,
    likes: 240000,
    comments: 11500,
    tags: ["뷰티", "홈케어", "리프팅", "괄사마사지", "V라인치트키", "가성비"],
    url: "https://www.xiaohongshu.com/search_result?keyword=%E6%B0%9B%E5%9B%B4%E6%84%9F%E5%A6%86%E5%AE%B9",
    highlight: "구독자 18만 대비 조회수 320만(1,777% 떡상). 퇴근 후 침대에 누워서 할 수 있는 초간단 V라인 관리법.",
    avatar: "🧚‍♀️"
  },
  {
    id: "xhs_03",
    name: "居家美学 (감성 인테리어 & 가젯)",
    handle: "@home_aesthetics",
    platform: "xiaohongshu",
    platformName: "샤오홍슈",
    platformIcon: "📕",
    category: "생활꿀템 / 인테리어",
    subscribers: 850000,
    avgViews: 2900000,
    likes: 310000,
    comments: 8900,
    tags: ["생활꿀템", "인테리어", "가성비소품", "삶의질상승", "감성가젯"],
    url: "https://www.xiaohongshu.com/search_result?keyword=%E5%B1%85%E5%AE%B6%E5%A5%BD%E7%89%A9",
    highlight: "호텔 같은 무드를 연출하는 가성비 조명과 수납 꿀템으로 2030 여성 구매 전환율 1등.",
    avatar: "🕯️"
  },

  // 📸 [인스타그램 릴스 / Instagram Reels]
  {
    id: "ig_01",
    name: "오늘의 꿀템집",
    handle: "@today_gooditem_kr",
    platform: "instagram",
    platformName: "인스타",
    platformIcon: "📸",
    category: "생활꿀템 / 쇼핑",
    subscribers: 1420000,
    avgViews: 3800000,
    likes: 190000,
    comments: 6800,
    tags: ["생활꿀템", "쿠팡소싱", "삶의질상승", "자취템", "가성비", "올리브영"],
    url: "https://www.instagram.com/explore/tags/%EA%BF%80%ED%85%9C%EC%B6%94%EC%B2%9C/",
    highlight: "15초 안에 문제점 제시 ➔ 사용 모습 ➔ 감탄 반응으로 끝내는 홈쇼핑형 릴스의 절대 강자.",
    avatar: "🛍️"
  },
  {
    id: "ig_02",
    name: "글로우 에스테틱",
    handle: "@glow_v_line",
    platform: "instagram",
    platformName: "인스타",
    platformIcon: "📸",
    category: "뷰티 / 리프팅",
    subscribers: 220000,
    avgViews: 3500000,
    likes: 240000,
    comments: 8900,
    tags: ["뷰티", "리프팅", "비포애프터", "홈케어", "페이스요가", "올리브영"],
    url: "https://www.instagram.com/explore/tags/%ED%99%88%EC%BC%80%EC%96%B4%EB%A3%A8%ED%8B%B4/",
    highlight: "구독자 22만인데 조회수 350만(1,590% 떡상). 반쪽 얼굴만 리프팅 테이프 붙이고 비교하는 릴스 영상 폭발.",
    avatar: "🌸"
  },
  {
    id: "ig_03",
    name: "바이럴 밈 큐레이터",
    handle: "@viral_meme_today",
    platform: "instagram",
    platformName: "인스타",
    platformIcon: "📸",
    category: "유머 / 밈",
    subscribers: 680000,
    avgViews: 2100000,
    likes: 180000,
    comments: 5200,
    tags: ["유머", "바이럴밈", "인기오디오", "릴스떡상", "공감숏폼"],
    url: "https://www.instagram.com/explore/tags/%EB%A6%B4%EC%8A%A4%EB%96%A1%EC%83%81/",
    highlight: "지금 인스타에서 가장 조회수 잘 터지는 릴스 배경음악(Trending Audio) 템플릿 실시간 공유.",
    avatar: "🔥"
  },

  // 🧵 [스레드 / Threads]
  {
    id: "th_01",
    name: "숏폼 연구소 김소장",
    handle: "@shortform_lab",
    platform: "threads",
    platformName: "스레드",
    platformIcon: "🧵",
    category: "마케팅 / 알고리즘",
    subscribers: 145000,
    avgViews: 1200000,
    likes: 62000,
    comments: 3800,
    tags: ["알고리즘", "3초후킹법", "시청지속시간", "숏폼마케팅", "수익화"],
    url: "https://www.threads.net/search?q=%EC%87%BC%ED%8F%BC%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%8A%B8",
    highlight: "구독자 대비 조회수 827% 달성. 틱톡/릴스/쇼츠 알고리즘이 밀어주는 3초 후킹 첫 대사 50가지 타래 공유.",
    avatar: "🧠"
  },
  {
    id: "th_02",
    name: "노코드 쇼츠 자동화 부스터",
    handle: "@autoshorts_pro",
    platform: "threads",
    platformName: "스레드",
    platformIcon: "🧵",
    category: "AI자동화 / 부업",
    subscribers: 48000,
    avgViews: 950000,
    likes: 54000,
    comments: 4200,
    tags: ["AI자동화", "노코드쇼츠", "1인창업", "부업", "수익화루트"],
    url: "https://www.threads.net/search?q=%EC%87%BC%ED%8F%BC%EC%9E%90%EB%8F%99%ED%99%94",
    highlight: "구독자 4.8만 소형 계정이지만 조회수 95만(1,979% 폭발적 떡상)! 하루 30분 만에 숏폼 3편 뽑는 워크플로우 대방출.",
    avatar: "⚡"
  },
  {
    id: "th_03",
    name: "글로벌 소싱 헌터",
    handle: "@china_sourcing_kr",
    platform: "threads",
    platformName: "스레드",
    platformIcon: "🧵",
    category: "이커머스 / 소싱",
    subscribers: 89000,
    avgViews: 1100000,
    likes: 48000,
    comments: 2900,
    tags: ["쿠팡소싱", "도우인히트상품", "중국소싱", "생활꿀템", "가성비"],
    url: "https://www.threads.net/search?q=%EC%83%81%ED%92%88%EC%86%8C%EC%8B%B1",
    highlight: "도우인에서 어제 터진 뷰티/생활용품을 한국 쿠팡 로켓배송에 가장 빠르게 소싱하는 비밀 채널 분석.",
    avatar: "🎯"
  }
];
